#!/bin/sh
#
# server

set -e

# make sure everything is up to date
script/bootstrap

#kill all processes using port 3000
ps -ef | grep unicorn | grep -v grep | while read CMD PID USER; do
  echo "Killing server process: $PID..." && kill -9 $PID
done

export PORT=3000

exec bin/foreman start