#!/bin/sh                                                                                                                                           
#                                                                                                                                                   
# ss

script/seed && script/server