---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: db01
  domain: fitly.org
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-20c66545
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - fitly_production_default
  - fitly_production_db01
  - fitly_production_redis
  - fitly_production_redis_master
  - fitly_production_collectd
  - fitly_production_monit
  external_host: ec2-50-16-161-166.compute-1.amazonaws.com
  external_ip: 50.16.161.166
  internal_host: ip-10-194-194-9.ec2.internal
  internal_ip: 10.194.194.9
  zone: us-east-1c
  platform: linux
  root_device_type: instance-store
  provider: aws
- !ruby/object:Rubber::Configuration::InstanceItem
  name: fe02
  domain: fitly.org
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: sidekiq
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-59ac133b
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - fitly_production_default
  - fitly_production_fe02
  - fitly_production_web
  - fitly_production_app
  - fitly_production_unicorn
  - fitly_production_nginx
  - fitly_production_sidekiq
  - fitly_production_collectd
  - fitly_production_monit
  external_host: ec2-174-129-141-75.compute-1.amazonaws.com
  external_ip: 174.129.141.75
  internal_host: ip-10-78-246-174.ec2.internal
  internal_ip: 10.78.246.174
  zone: us-east-1c
  platform: linux
  root_device_type: instance-store
  provider: aws
- !ruby/object:Rubber::Configuration::InstanceItem
  name: fe01
  domain: fitly.org
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: sidekiq
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-33c79a51
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - fitly_production_default
  - fitly_production_fe01
  - fitly_production_web
  - fitly_production_app
  - fitly_production_unicorn
  - fitly_production_nginx
  - fitly_production_sidekiq
  - fitly_production_collectd
  - fitly_production_monit
  external_host: ec2-184-73-98-84.compute-1.amazonaws.com
  external_ip: 184.73.98.84
  internal_host: ip-10-244-223-70.ec2.internal
  internal_ip: 10.244.223.70
  zone: us-east-1c
  platform: linux
  root_device_type: instance-store
  provider: aws
- !ruby/object:Rubber::Configuration::InstanceItem
  name: tools
  domain: fitly.org
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: jenkins
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  instance_id: i-3a585f50
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - fitly_production_default
  - fitly_production_tools
  - fitly_production_web_tools
  - fitly_production_nginx
  - fitly_production_graylog_web
  - fitly_production_graylog_server
  - fitly_production_graylog_mongodb
  - fitly_production_mongodb
  - fitly_production_graylog_elasticsearch
  - fitly_production_elasticsearch
  - fitly_production_collectd
  - fitly_production_monit
  external_host: ec2-72-44-60-63.compute-1.amazonaws.com
  external_ip: 72.44.60.63
  internal_host: ip-10-32-178-223.ec2.internal
  internal_ip: 10.32.178.223
  zone: us-east-1c
  platform: linux
  root_device_type: instance-store
  provider: aws
- volumes: {}
  static_ips: {}
